In [13]:
import numpy as np
x1=np.arange(-3,3,1)
x2=np.arange(-3,3,1)
print(x1)
print(x2)

[-3 -2 -1  0  1  2]
[-3 -2 -1  0  1  2]


In [11]:
Y= np.array ([x1,x2])
Y

array([[-3, -2, -1,  0,  1,  2],
       [-3, -2, -1,  0,  1,  2]])

In [12]:
X = Y.T
X

array([[-3, -3],
       [-2, -2],
       [-1, -1],
       [ 0,  0],
       [ 1,  1],
       [ 2,  2]])

In [86]:
#You must access the row
x=[x1,x2]
x=X[0]
x

array([-3, -3])

In [75]:
x1=[x[0] for x in X]
x1

[-3, -2, -1, 0, 1, 2]

In [82]:
x1=X[:,1]
x1


array([-3, -2, -1,  0,  1,  2])