In [2]:
#Ejercicios Numpy
#importar numpy
import numpy as np

In [3]:
"""
Crear un numpy array que tenga la siguiente estructura
[[1,6,11],
 [2,7,12],
 [3,8,13],
 [4,9,14],
 [5,10,15]]
 llamadolor array
 """
array=np.array([
    [1,6,11],
 [2,7,12],
 [3,8,13],
 [4,9,14],
 [5,10,15]
])
array

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [4]:
#averigua la forma del array
array.shape

(5, 3)

In [6]:
#Dimenciones del array
array.ndim

2

In [5]:
#seleccionar la segunda columna del array
array
array[:,1]


array([ 6,  7,  8,  9, 10])

In [5]:
#Crear un vector con los valores de 15 a 55 y llamalo
#array2
array2=np.arange(15,56)
array2

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

In [6]:
#Asignar el numero 23 a la 5 posicion del array2
array2[4]=23
array2

array([15, 16, 17, 18, 23, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

In [6]:
#Convierte el array2 alrevez
array2[::-1] 

array([55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39,
       38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22,
       21, 20, 23, 18, 17, 16, 15])

In [20]:
#obtener los primeros 5 elementos pares de array2
#Empesamos con el elemento uno para empezar con 
#pares [1::]y vamos de 2 en 2[::2] dos los primeros 5 elemntos[:5] 
pares_5=array2[1::][:2][:5]
pares_5
# se puede  expresar
pares_5=array2[1::2][:5]
pares_5

array([16, 18, 20, 22, 24])

In [7]:
#Crear una matriz diagonal con los cinco primeros 
#elementos del array2
matriz_diag=np.diag(array2[1::][::2][:5])
matriz_diag

array([[16,  0,  0,  0,  0],
       [ 0, 18,  0,  0,  0],
       [ 0,  0, 20,  0,  0],
       [ 0,  0,  0, 22,  0],
       [ 0,  0,  0,  0, 24]])

In [21]:
matriz_diag.ndim

2

In [22]:
np.random.random?

In [8]:
#Crear una matriz de numeros aleatoreos de 5 por 3
#llamada matriz
matriz=np.random.random((5,3))
matriz

array([[0.5295469 , 0.27669945, 0.46882137],
       [0.69957052, 0.25589445, 0.33119389],
       [0.85341557, 0.53450513, 0.49765661],
       [0.1487772 , 0.39535759, 0.76128801],
       [0.12376601, 0.64761248, 0.73211507]])

In [27]:
matriz_diag.shape
matriz

(5, 5)

In [28]:
matriz@matriz_diag

ValueError: shapes (5,3) and (5,5) not aligned: 3 (dim 1) != 5 (dim 0)

In [9]:
#Se debe aplicar la transpuesta a la matriz para que 
# el numero de filas sea el mismo al de las columnas
matriz.T@matriz_diag

array([[ 8.47275043, 12.59226942, 17.06831134,  3.2730984 ,  2.97038434],
       [ 4.4271912 ,  4.60610018, 10.69010253,  8.69786691, 15.54269944],
       [ 7.50114197,  5.96148998,  9.95313219, 16.74833615, 17.5707617 ]])