In [1]:
import sys
import numpy as np


In [2]:
#Crear array de numpy array de dimencion uno 
array_1d=np.array([4,5,3])
type(array_1d)


numpy.ndarray

In [3]:
#Saber cuantas dimenciones tiene este arreglo 
array_1d.ndim

1

In [4]:
#Saber la forma de un  array(filas,columnas)
array_1d.shape

(3,)

In [6]:
#Una matriz es un array de arrays
matriz=np.array([
    [1,2,3],
    [4,5,6]
])
matriz

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
#Saber las dimenciones de la matriz
matriz.ndim

2

In [8]:
#Saber la forma de la matriz
matriz.shape

(2, 3)

In [9]:
#Crear matriz de ceros
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
#Crear una matriz de unos
np.ones((2,1))

array([[1.],
       [1.]])

In [11]:
#Crear una matriz identidad
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.random.random((2,3))

array([[0.99933774, 0.82521013, 0.22508359],
       [0.93606022, 0.04764147, 0.29229804]])

In [16]:
#podemos leer texto desde numpy
#leemos un un archivo de texto 
!cat np_text.txt

1,2,3
43,2,3
34,1,1
0,1,1



In [18]:
np_text=np.genfromtxt("np_text.txt",delimiter=",")
np_text

array([[ 1.,  2.,  3.],
       [43.,  2.,  3.],
       [34.,  1.,  1.],
       [ 0.,  1.,  1.]])

In [19]:
lista_2d=[[1,2,3],[4,5,6]]
array_2d=np.array([[1,2,3],[4,5,6]])

In [21]:
#para sabber el tamaño en memoria ocupamos
sys.getsizeof(lista_2d)


80

In [22]:
sys.getsizeof(array_2d)

160

In [23]:
big_lista=list(range(1000000))
big_array=np.array(range(1000000))

In [24]:
sys.getsizeof(big_lista)

9000112

In [25]:
sys.getsizeof(big_array)

8000096

In [26]:
#Saber cuanto tiempo lleva en ejecutarse un proceso en python
%%timeit
sum(range(1000000))


17.3 ms ± 959 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [28]:
%%timeit
np.sum(np.arange(1000000))

2.74 ms ± 54.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [29]:
np.array([1.0,5.4]).dtype

dtype('float64')

In [30]:
#Para indicar el tipo de dato del array agregamos 
np.array([1.0,5.4],dtype=int).dtype

dtype('int64')

In [31]:
#En un arreglo de numpy todos los elementos son del 
#mismo tipo, si en un arreglo de numpy agregamos un 
#string todo el arreglo sera de strings
np.array([1.0,2.0,"patata"]).dtype

dtype('<U32')

In [32]:
%%timeit
["{}".format(i) for i in range(1000000)]


248 ms ± 16.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [37]:
#Numpy nos permite vectorizar funciones
f=np.vectorize(lambda x:"{}".format(x))

In [38]:
%%timeit
f(np.arange(1000000))

456 ms ± 6.74 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [2]:
#Crear una matriz de 3 filas por 4 columas
matriz_34=np.array([
    [1,2,3,4],[5,6,7,8],[9,10,11,12]
])
matriz_34

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
#Para acceder a la primer fila de la matriz
matriz_34[0]

array([1, 2, 3, 4])

In [4]:
#Para acceder a las dos primeras filas de la matriz
matriz_34[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
#Para acceder a los elementos de la segunda columna de
#la matriz
matriz_34[:,1]

array([ 2,  6, 10])

In [6]:
#Para acceder al segundo elemento de la segunda fila
matriz_34[1,1]

6

In [7]:
#Al usar los dos puntos nos devuelve una vista de la 
#matriz una copia
matriz_34[:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
#Si intentamos modificar un elemento no lo haria 
#pues es una copia
seleccion=matriz_34[1,3]
print(seleccion)
seleccion=100
matriz_34

8


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
#Posemos modificar la matriz seleccionando una seccion
seccion=matriz_34[:2]
seccion

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
#Modificamos el elemento 0,0
seccion[0,0]=100
matriz_34

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [12]:
#Matriz 3 por 2
matriz_32=np.array([
    [1,4],[2,4],[5,0]
])
matriz_32


array([[1, 4],
       [2, 4],
       [5, 0]])

In [13]:
#Podemos crear un filtro con la matriz
indice_filtrado=matriz_32>2
indice_filtrado

array([[False,  True],
       [False,  True],
       [ True, False]])

In [14]:
#Para obtener los elemtos que cumplen esto se realiza
matriz_32[indice_filtrado]

array([4, 4, 5])

In [15]:
#Operaciones con array 
array1=np.array([
    [1,2],[3,4]
])
array2=np.array([
    [23,5],[3,0]
])

In [16]:
#Sumar array 
array1+array2

array([[24,  7],
       [ 6,  4]])

In [17]:
#Multiplicar array elemento a elemento
array1*array2

array([[23, 10],
       [ 9,  0]])

In [18]:
#Multiplicacion de matricial de arrays
array1@array2

array([[29,  5],
       [81, 15]])